# Generated by Django 5.0.4 on 2024-05-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('population', '0002_remove_populationdata_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='populationdata',
            name='population',
        ),
        migrations.RemoveField(
            model_name='populationdata',
            name='year',
        ),
        migrations.AddField(
            model_name='populationdata',
            name='age_group',
            field=models.CharField(default='0-99', max_length=10),
        ),
        migrations.AddField(
            model_name='populationdata',
            name='female_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='populationdata',
            name='male_percentage',
            field=models.FloatField(default=0),
        ),
    ]
